server:
    port: 8081

spring:
    rabbitmq:
        addresses: 192.168.159.3:5672
        username: admin
        password: admin
        virtual-host: /
        connection-timeout: 15000
        listener:
          simple:
              concurrency: 5
              max-concurrency: 10
              acknowledge-mode: manual
              prefetch: 1 #限流
    http:
        encoding:
            charset: UTF-8
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null

