server:
  port: 18081

spring:
  application:
    name: "client-2"
  boot:
    admin:
      client:
        url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
