server:
  port: 8081

spring:
  application:
    name: "client-1"
  boot:
    admin:
      client:
        url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
