management:
    endpoint:
        shutdown:
            enabled: false
    endpoints:
        web:
            exposure:
                include: "*"

application:
    root:
        username: admin
        password: admin
