server:
    port: 0

spring:
    application:
        name: user-service
    devtools:
        livereload:
            port: 0

eureka:
    instance:
        hostname: localhost
        appname: ${spring.application.name}
        #Eureka 客户端像服务端发送心跳的时间间隔，单位为秒（默认是30秒）
        lease-renewal-interval-in-seconds: 1
        #Eureka 服务端收到最后一次心跳后等待时间上线，单位为秒（默认是90秒），超时将剔除服务
        #lease-expiration-duration-in-seconds: 2
    client:
        #表示是否将自己注册进EurekaServer默认为true
        register-with-eureka: true
        fetch-registry: false
        service-url:
            defaultZone: "http://eureka1.service.com:2001/eureka/,http://eureka2.service.com:2002/eureka/,http://eureka3.service.com:2003/eureka/"

