server:
    port: 2001

spring:
    application:
        name: eureka
eureka:
    instance:
        lease-renewal-interval-in-seconds: 2
        lease-expiration-duration-in-seconds: 5
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
    client:
        register-with-eureka: true
        # 要不要去注册中心获取其他服务的地址
        fetch-registry: true
        service-url:
            defaultZone: "http://eureka2.service.com:2002/eureka/,http://eureka3.service.com:2003/eureka/"
    server:
        # 当从其他节点同步实例信息为空时等待的时间
        wait-time-in-ms-when-sync-empty: 0
        eviction-interval-timer-in-ms: 5000
        response-cache-update-interval-ms: 5000
        use-read-only-response-cache: false
