server:
    port: 18080

spring:
    application:
        name: service-1
    devtools:
        livereload:
            enabled: false

eureka:
    instance:
        hostname: localhost
        appname: ${spring.application.name}
        prefer-ip-address: true
        #Eureka 客户端像服务端发送心跳的时间间隔，单位为秒（默认是30秒）
        #lease-renewal-interval-in-seconds: 1
        #Eureka 服务端收到最后一次心跳后等待时间上线，单位为秒（默认是90秒），超时将剔除服务
        #lease-expiration-duration-in-seconds: 2
    client:
        #表示是否将自己注册进EurekaServer默认为true
        register-with-eureka: true
        #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
        fetch-registry: true
        service-url:
            defaultZone: "http://eureka1.service.com:2001/eureka,http://eureka2.service.com:2002/eureka,http://eureka3.service.com:2003/eureka"

