server:
    port: 8097
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: https://gitee.com/goffather/springboot-study.git
                    basedir: D:/tmp/configcenter
                    username: ${env.GIT_USER}
                    password: ${env.GIT_PASSWORD}
                    default-label: master
    rabbitmq:
        addresses: 192.168.159.3:5672
        username: admin
        password: admin

eureka:
    instance:
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
        appname: ${spring.application.name}
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 2
        lease-expiration-duration-in-seconds: 5
    client:
        fetch-registry: false
        register-with-eureka: true
        service-url:
            defaultZone: "http://eureka1.service.com:2001/eureka/,http://eureka2.service.com:2002/eureka/,http://eureka3.service.com:2003/eureka/"

management:
  endpoints:
    web:
        exposure:
            include: "*"
