server:
    port: 8080
spring:
  datasource:
#      url: jdbc:h2:~/h2/data
      url: "jdbc:h2:tcp://127.0.0.1/~/h2/data"
      driver-class-name: org.h2.Driver
      password: 123456
      data-username: sa

  h2:
    console:
        path: /h2-console
        enabled: true
        settings:
            web-allow-others: true
  jpa:
      database: h2
      hibernate:
          ddl-auto: update
      show-sql: true
      open-in-view: false

