server:
    port: 8080
    servlet:
        encoding:
            charset: UTF-8

spring:
    rabbitmq:
        addresses: 192.168.159.3:5672
        username: admin
        password: admin
        virtual-host: /
        connection-timeout: 15000
        publisher-confirm-type: correlated
        publisher-returns: true
        template:
            mandatory: true
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null

